<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.gitee.wb04307201</groupId>
    <artifactId>sql-forge-parent</artifactId>
    <version>1.0-SNAPSHOT</version>

    <packaging>pom</packaging>
    <url>
        https://gitee.com/wb04307201/sql-forge
    </url>
    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>
    <developers>
        <developer>
            <name>wubo</name>
            <email>wubo_aaa@163.com</email>
            <url>https://gitee.com/wb04307201</url>
        </developer>
    </developers>

    <modules>
        <module>sql-forge-core</module>
        <module>sql-forge-calcite</module>
        <module>sql-forge-record</module>
        <module>sql-forge-entity</module>
        <module>sql-forge-template</module>
        <module>sql-forge-console</module>
        <module>sql-forge-ai</module>
        <module>sql-forge-spring-boot-autoconfigure</module>
        <module>sql-forge-ai-spring-boot-autoconfigure</module>
        <module>sql-forge-spring-boot-starter</module>
        <module>sql-forge-test</module>
        <module>sql-forge-ai-test</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>3.5.9</spring-boot.version>
        <lombok.version>1.18.42</lombok.version>
        <jakarta.version>3.2.0</jakarta.version>
        <jsqlparser.version>5.3</jsqlparser.version>
        <enjoy.version>5.2.5</enjoy.version>
        <mvel2.version>2.5.2.Final</mvel2.version>
        <calcite.version>1.41.0</calcite.version>
        <spring-ai.version>1.1.2</spring-ai.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring-ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>jakarta.persistence</groupId>
                <artifactId>jakarta.persistence-api</artifactId>
                <version>${jakarta.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.jsqlparser</groupId>
                <artifactId>jsqlparser</artifactId>
                <version>${jsqlparser.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mvel</groupId>
                <artifactId>mvel2</artifactId>
                <version>${mvel2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.calcite</groupId>
                <artifactId>calcite-core</artifactId>
                <version>${calcite.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>