spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./sql-forge-test/data/testdb;AUTO_SERVER=TRUE
    username: sa
  flyway:
    placeholder-replacement: false

sql:
  forge:
    schemata:
      - PUBLIC
    calcite:
      enabled: true
      configuration: classpath:model.json
      schemata:
        - MYSQL
        - POSTGRES
    api:
      database:
        enabled: true
        select-only: false
    apiKeys:
      - test


server:
  port: 8081