spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./sql-forge-test/data/testdb;AUTO_SERVER=TRUE
    username: sa
  flyway:
    placeholder-replacement: false
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus

sql:
  forge:
    calcite:
      enabled: true
      configuration: classpath:model.json
    api:
      database:
        enabled: true
        select-only: false
    ai:
      enabled: true
server:
  port: 8089



