spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: sql-forge-mcp-server
        version: 1.5.12

logging:
  pattern:
    console:
  file:
    name: ./mcp/sql-forge-mcp-server.log
