spring:
  main:
    web-application-type: none
    banner-mode: off
  ai:
    mcp:
      server:
        name: sql-forge-mcp-server
        version: 1.6.1

logging:
  level:
    cn.wubo.sql.forge: INFO
    org.springframework.ai: INFO
  file:
    name: ./mcp/sql-forge-mcp-server.log